[build]
builder = "nixpacks"
watchPatterns = ["**/*"]
buildCommand = "npm run build"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { 
  NODE_ENV = "production",
  PORT = "3001",
  VITE_STORAGE_TYPE = "api",
  VITE_API_BASE_URL = "https://$RAILWAY_PUBLIC_DOMAIN/api"
}